name: sonobuoy
baseurl: /sonobuoy
google_analytics: FILL_OUT
latest: v0.11.1
versions:
- v0.11.1
versioning: false
logo: assets/img/logo.svg
exclude:
- gen_version.sh
- v0.10.0
- v0.9.0
- v0.8.0
plugins:
- jekyll-redirect-from
contact:
  google: https://groups.google.com/forum/#!forum/heptio-sonobuoy
  github: https://github.com/heptio/sonobuoy
  twitter: https://twitter.com/heptiosonobuoy
  slack: https://kubernetes.slack.com/messages/sonobuoy
defaults:
- scope:
    path: latest
  values:
    version: latest
    gh: https://github.com/heptio/sonobuoy/tree/master

